### PR TITLE
Adds DWT snippet 1.

### PR DESCRIPTION
**Pull request by kntroh**
Adds snippet for test of V4 bitmap.

To distinguish SWT snippets and DWT snippets, I added `Dwt` to file name.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
I'm starting to think it would be a good idea to add something else to the name than just a number to give a hint what the snippet is about. I'm thinking something like `SnippetDwtBitmapV4`.

Also please add this to the commit message, something like: "Add DWT snippet for reading Bitmap V4".

**Comment by kntroh** [comment]
Ok, I updated pull request.

**Comment by jacob-carlborg** [comment]
Could you please squash your commits?

**Comment by kntroh** [comment]
I squashed now.

**Comment by jacob-carlborg** [comment]
Awesome, thanks.

**Pull request merged**
